version: '3.9'
services:
  website:
    build: .
    image: website:prd
    container_name: website-jonnattan
    restart: always
    env_file:
      - ../envs/website.env
    ports:
      - "8080:80"
    networks:
      - db-net
networks:
  db-net:
