version: '3.9'
services:
  compilate-node-20:
    image: node20-compilador:v1
    container_name: compilador_node_20
    volumes:
        - ./:/usr/src/app
    env_file:
      - .envs-dev
    ports:
      - "8080:3000"
    networks:
      - db-net
networks:
  db-net:
