version: '3.9'
services:
  website:
    container_name: website-jonnattan
    image: website:dev
    build: 
      dockerfile: Dockerfile-dev
    restart: always
    volumes:
        - ./:/usr/src/app
    env_file:
      - ../envs/website.env
    ports:
      - "8080:3000"
    networks:
      - db-net
    # command: tail -f /home/logia/requirements.txt
networks:
  db-net:
