version: '3.9'
services:
  web:
    image: website:v2.1
    container_name: website
    restart: always
    env_file:
      - .env
    ports:
      - "8080:80"
    networks:
      - db-net
networks:
  db-net:
