services:
  website:
    image: jonnattangc/website:1.0.0
    container_name: website
    restart: always
    env_file:
      - ../envs/website.env
    ports:
      - "8080:80"
    networks:
      - db-net
networks:
  db-net:
